### ISSUE TITLE
Support for also bundling the importmaps dependencies?

### ISSUE THREAD

**Issue by schlichtanders** [FlorianRappl/parcel-plugin-import-maps#1]
Hi there,

I am using Parcel to bundle my entire website and would like to switch from npm dependencies to a plain importmap (inlined into the index.html) so that everything is immediately browser-ready.

I only found this plugin about parcel and import-maps, but apparently it does not bundle the importmap definitions. I am looking for the exakt opposite, that importmaps are also bundled, just like npm dependencies would be bundled.

Could this be added as an option to the package? Or is there alternative?

**Comment by FlorianRappl** [comment]
Any reason for sticking with an outdated unsupported bundler? Why not go for Parcel 2, Vite, esbuild, ... you name it?

I don't think it can be added - because even if generally it could be supported, Parcel 1 has no real configuration and there are problems already getting the importmap from the HTML (but even without that requirement it would be pretty difficult).

What I would recommend is to use the `parcel-plugin-codegen` and parse the HTML / get the dependencies in with this approach.

More details about codegen you can find here: https://dev.to/florianrappl/getting-bundling-superpowers-using-codegen-2no8

Advantage is that this plugin is available for essentially all bundles; making this part of your code quite transportable.

**Comment by schlichtanders** [comment]
thank you for your hint. I was not aware that this is for parcel 1 and outdated. Maybe archive it? That would be a clear sign.

**Comment by FlorianRappl** [comment]
Yeah agreed (well - all the commits say 4 years and the project itself is still valid / just that it's quite uncommon that people still use Parcel v1; it was a great bundler but it has not received any updates and has fallen behind)

**Comment by FlorianRappl** [comment]
(the hint with the codegen loader is still valid though - I think this way you can already solve it in P2, too)
